In [1]:
import numpy as np

In [5]:
a = np.arange(6)

In [6]:
a

array([0, 1, 2, 3, 4, 5])

In [9]:
b= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
# b=b.reshape(6,3)

In [10]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [11]:
np.argsort(b)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [12]:
np.argmin(b)

np.int64(0)

In [13]:
np.argmax(b)

np.int64(17)