In [1]:
import numpy as np 


In [2]:
arr = np.array([[1,2,3],[5,6,7],[1,2,3]])


In [3]:
arr


array([[1, 2, 3],
       [5, 6, 7],
       [1, 2, 3]])

In [4]:
arr.sum(axis = 1)

array([ 6, 18,  6])

In [5]:
arr.sum(axis = 0)

array([ 7, 10, 13])

In [6]:
arr1 = np.array([[11,22,33],[55,66,77],[11,22,33]])


In [7]:
np.dot(arr,arr1.transpose())

array([[ 154,  418,  154],
       [ 418, 1210,  418],
       [ 154,  418,  154]])

In [8]:
np.cross(arr,arr1)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])