Basic Functions

In [1]:
import numpy as np 
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [2]:
arr.shape

(2, 4)

In [3]:
arr.dtype

dtype('int64')

In [4]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [5]:
np.empty((3,4))

array([[9.23920699e-312, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [2.04718339e-306, 2.32153320e-056, 3.79025974e+179,
        3.69846728e-057],
       [5.68425163e-062, 1.87087794e-051, 1.64798425e+185,
        2.10816595e-052]])

In [6]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr*arr

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [8]:
arr+arr

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [9]:
arr/arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Slicing

In [10]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [14]:
arr2 = arr1[2:6]
print(arr2)

[3 4 5 6]


In [15]:
arr2[0] =33

In [16]:
arr2

array([33,  4,  5,  6])

In [17]:
arr1

array([ 1,  2, 33,  4,  5,  6,  7,  8,  9])

In [20]:
arr3 = arr1[2:6].copy()

In [21]:
arr3

array([33,  4,  5,  6])

In [ ]:
arr3[0